Make sure the OS is not Windows before checking for root
When checking for Root on a non Windows OS we get:
AttributeError: 'module' object has no attribute 'geteuid'

Instead of correctly raising an OS exception.